# Extract features (single subject)

Feature extraction (for later training and/or classifying).

In [ ]:
%load_ext autoreload
%autoreload 2

from pyfix import extract
from pyfix.util import SegType
import os.path as op

In [ ]:
dhcpdir = '/Users/seanf/data/neofmri_2nd_release_rerun2/sub-CC00108XX09/ses-36800'

features = extract.extract_features(
    fixdir='/Users/seanf/scratch/testing-pyfix/pyfix',
    func=op.join(dhcpdir, 'ica/func_filtered.nii.gz'),
    func_brainmask=op.join(dhcpdir, 'fix/mask.nii.gz'),
    struct=op.join(dhcpdir, 'fix/reg/highres.nii.gz'),
    struct2func_xfm=op.join(dhcpdir, 'fix/reg/highres2example_func.mat'),
    struct_dseg=op.join(dhcpdir, 'fix/reg/highres_pveseg.nii.gz'),
    ic_timeseries=op.join(dhcpdir, 'ica/melodic_mix'),
    ic_map=op.join(dhcpdir, 'ica/melodic_IC.nii.gz'),
    mot_param=op.join(dhcpdir, 'mcdc/func_mcdc.eddy_parameters'),
    struct_dseg_type=SegType.fsl_fast,
    hp_fwhm=150,
)

Table of legacy features:

In [5]:
features.head()

,nic,arvswgn:0,arvswgn:1,arfull:0,arfull:1,arfull:2,arfull:3,arfull:4,entropy:0,entropy:1,...,sagmasks:62,sagmasks:63,sagmasks:64,sagmasks:65,sagmasks:66,sagmasks:67,sagmasks:68,sagmasks:69,sagmasks:70,sagmasks:71
0,583.0,-0.005714,0.244681,0.248129,-0.867043,0.235137,-1.065443,0.228824,3.184446,0.010876,...,0.033955,0.002515,0.014357,-0.004184,0.000780,0.000641,0.022802,0.001076,0.017463,-0.006355
1,583.0,-0.002609,0.165551,0.165433,-0.913507,0.164156,-0.993779,0.087873,3.414057,0.003393,...,0.041132,0.003271,0.013216,-0.019830,0.001396,0.000974,0.044144,0.005014,0.017516,-0.021840
2,583.0,-0.000873,0.255459,0.255725,-0.862649,0.254352,-0.799426,-0.073290,3.218573,0.013414,...,0.014999,-0.000259,0.011645,-0.006855,0.000590,0.000435,0.016285,-0.000074,0.015233,-0.010341
3,583.0,-0.001897,0.246439,0.249950,-0.865992,0.241311,-0.704997,-0.185908,2.827059,0.020899,...,0.077920,0.009224,0.023115,-0.005142,0.002233,0.001968,0.065866,0.009945,0.027683,-0.013467
4,583.0,-0.002441,0.490469,0.488339,-0.715156,0.487470,-0.745323,0.042183,3.009137,0.028873,...,0.048417,0.004432,0.015953,-0.014338,0.001345,0.000849,0.041852,0.004654,0.019110,-0.018085

In [84]:
! tree -lrt /Users/seanf/scratch/testing-pyfix/pyfix

/Users/seanf/scratch/testing-pyfix/pyfix
├── func_clean.nii.gz
├── features.csv
├── icmap0_abs.nii.gz
├── icmap0.nii.gz
├── dummym.nii.gz
├── dummyd.nii.gz
├── dummy2.nii.gz
├── std1mm2exfunc3dil2.nii.gz
├── std1mm2exfunc3dil.nii.gz
├── std1mm2exfunc3.nii.gz
├── std1mm2exfunc2dil2.nii.gz
├── std1mm2exfunc2dil.nii.gz
├── std1mm2exfunc2.nii.gz
├── std1mm2exfunc1dil2.nii.gz
├── std1mm2exfunc1dil.nii.gz
├── std1mm2exfunc1.nii.gz
├── std1mm2exfunc0dil2.nii.gz
├── std1mm2exfunc0dil.nii.gz
├── std1mm2exfunc0.nii.gz
├── struct2std.mat
├── std2struct.mat
├── std2func.mat
├── maske5.nii.gz
├── maske4.nii.gz
├── maske3.nii.gz
├── edge5.nii.gz
├── edge4.nii.gz
├── edge3.nii.gz
├── maske2.nii.gz
├── maske1.nii.gz
├── edge2.nii.gz
├── edge1.nii.gz
├── func_mean.nii.gz
├── func_dseg.nii.gz
├── func_tsnr.nii.gz
└── func_std.nii.gz

0 directories, 36 files

## Extract features from FEAT dir

Extract features from files in a FEAT directory where ICA has been run.

In [ ]:
featdir = '/Users/seanf/data/fsldata/Rest_MB6.feat'

features = extract.from_feat_dir(featdir)

In [139]:
! tree {featdir}/pyfix

/Users/seanf/data/fsldata/Rest_MB6.feat/pyfix
├── dummy2.nii.gz
├── dummyd.nii.gz
├── dummym.nii.gz
├── edge1.nii.gz
├── edge2.nii.gz
├── edge3.nii.gz
├── edge4.nii.gz
├── edge5.nii.gz
├── fastsg_mixeltype.nii.gz
├── fastsg_pve_0.nii.gz
├── fastsg_pve_1.nii.gz
├── fastsg_pve_2.nii.gz
├── fastsg_pveseg.nii.gz
├── fastsg_seg.nii.gz
├── features.csv
├── func_dseg.nii.gz
├── func_mean.nii.gz
├── icmap0.nii.gz
├── icmap0_abs.nii.gz
├── maske1.nii.gz
├── maske2.nii.gz
├── maske3.nii.gz
├── maske4.nii.gz
├── maske5.nii.gz
├── std1mm2exfunc0.nii.gz
├── std1mm2exfunc0dil.nii.gz
├── std1mm2exfunc0dil2.nii.gz
├── std1mm2exfunc1.nii.gz
├── std1mm2exfunc1dil.nii.gz
├── std1mm2exfunc1dil2.nii.gz
├── std1mm2exfunc2.nii.gz
├── std1mm2exfunc2dil.nii.gz
├── std1mm2exfunc2dil2.nii.gz
├── std1mm2exfunc3.nii.gz
├── std1mm2exfunc3dil.nii.gz
└── std1mm2exfunc3dil2.nii.gz

0 directories, 36 files

## Custom feature extractor/s

Add custom feature extractors.  A custom feature extractor is a method that is decorated with the `@feature_extractor` decorator, accepts the the pyfix data dictionary as input (to be replaced with a dataclass), and returns a feature.  Allowed return types are list, scalar, dictionary, and pandas `Series`.

In [ ]:
from pyfix.feature import feature_extractor
import pandas as pd

@feature_extractor
def grot(data):
    return [1, 2, 3]

@feature_extractor
def grot2(data):
    return 4

@feature_extractor
def grot3(data):
    return {'poo': 5}

@feature_extractor
def grot4(data):
    return pd.Series({'pop': 5})

dhcpdir = '/Users/seanf/data/neofmri_2nd_release_rerun2/sub-CC00108XX09/ses-36800'

features = extract.extract_features(
    fixdir='/Users/seanf/scratch/testing-pyfix/pyfix',
    func=op.join(dhcpdir, 'ica/func_filtered.nii.gz'),
    func_brainmask=op.join(dhcpdir, 'fix/mask.nii.gz'),
    struct=op.join(dhcpdir, 'fix/reg/highres.nii.gz'),
    struct2func_xfm=op.join(dhcpdir, 'fix/reg/highres2example_func.mat'),
    struct_dseg=op.join(dhcpdir, 'fix/reg/highres_pveseg.nii.gz'),
    ic_timeseries=op.join(dhcpdir, 'ica/melodic_mix'),
    ic_map=op.join(dhcpdir, 'ica/melodic_IC.nii.gz'),
    mot_param=op.join(dhcpdir, 'mcdc/func_mcdc.eddy_parameters'),
    struct_dseg_type=SegType.fsl_fast,
    hp_fwhm=150,
)

In [141]:
features.head()

,nic,arvswgn:0,arvswgn:1,arfull:0,arfull:1,arfull:2,arfull:3,arfull:4,entropy:0,entropy:1,...,sagmasks:68,sagmasks:69,sagmasks:70,sagmasks:71,grot:0,grot:1,grot:2,grot2,poo,pop
0,583.0,-0.005714,0.244681,0.248129,-0.867043,0.235137,-1.065443,0.228824,3.184446,0.010876,...,0.022802,0.001076,0.017463,-0.006355,1.0,2.0,3.0,4.0,5.0,5.0
1,583.0,-0.002609,0.165551,0.165433,-0.913507,0.164156,-0.993779,0.087873,3.414057,0.003393,...,0.044144,0.005014,0.017516,-0.021840,1.0,2.0,3.0,4.0,5.0,5.0
2,583.0,-0.000873,0.255459,0.255725,-0.862649,0.254352,-0.799426,-0.073290,3.218573,0.013414,...,0.016285,-0.000074,0.015233,-0.010341,1.0,2.0,3.0,4.0,5.0,5.0
3,583.0,-0.001897,0.246439,0.249950,-0.865992,0.241311,-0.704997,-0.185908,2.827059,0.020899,...,0.065866,0.009945,0.027683,-0.013467,1.0,2.0,3.0,4.0,5.0,5.0
4,583.0,-0.002441,0.490469,0.488339,-0.715156,0.487470,-0.745323,0.042183,3.009137,0.028873,...,0.041852,0.004654,0.019110,-0.018085,1.0,2.0,3.0,4.0,5.0,5.0

# Train (group)
Train FIX on a group of labelled subjects.

Generate a table of files from legacy FIX directories.

In [142]:
from pyfix import train, legacy
import glob

file_table = legacy.generate_file_table(*glob.glob('/Users/seanf/data/HCP/fix_labels/*.ica'))
file_table.head()

,features,labels,subid
0,/Users/seanf/data/HCP/fix_labels/36.ica/fix/fe...,/Users/seanf/data/HCP/fix_labels/36.ica/hand_l...,0
1,/Users/seanf/data/HCP/fix_labels/22.ica/fix/fe...,/Users/seanf/data/HCP/fix_labels/22.ica/hand_l...,1
2,/Users/seanf/data/HCP/fix_labels/23.ica/fix/fe...,/Users/seanf/data/HCP/fix_labels/23.ica/hand_l...,2
3,/Users/seanf/data/HCP/fix_labels/37.ica/fix/fe...,/Users/seanf/data/HCP/fix_labels/37.ica/hand_l...,3
4,/Users/seanf/data/HCP/fix_labels/21.ica/fix/fe...,/Users/seanf/data/HCP/fix_labels/21.ica/hand_l...,4

Generate a `feature_table` that collates all the features from the files specified in the `file_table`.

In [143]:
training_data = train.collate_features(file_table)
training_data.head()

,nic,arvswgn:0,arvswgn:1,arfull:0,arfull:1,arfull:2,arfull:3,arfull:4,skewness,kurtosis,...,dim:0,dim:1,dim:2,dim:3,pixdim:0,pixdim:1,pixdim:2,pixdim:3,group,label
0,247,-0.004475,0.042334,0.038705,-0.98044,0.038703,-0.98781,0.007513,0.328840,2.6123,...,91,109,91,1200,2,2,2,0.72,0,True
1,247,-0.004769,0.036614,0.032718,-0.98349,0.032699,-1.00760,0.024518,-0.326090,2.0584,...,91,109,91,1200,2,2,2,0.72,0,True
2,247,-0.016596,0.132840,0.119340,-0.93838,0.118980,-0.98998,0.054986,-0.128070,2.1478,...,91,109,91,1200,2,2,2,0.72,0,True
3,247,-0.012649,0.101670,0.092065,-0.95282,0.091779,-1.00590,0.055716,0.295100,2.2495,...,91,109,91,1200,2,2,2,0.72,0,True
4,247,-0.009742,0.091605,0.081953,-0.95811,0.081886,-0.93078,-0.028525,0.024646,1.9019,...,91,109,91,1200,2,2,2,0.72,0,True

Train the classifier with LOO cross-validation for assessing generalisation error.  Any classifier that conforms to `scikit-learn` API can be used.

In [ ]:
from sklearn import svm, ensemble, neighbors, tree, neural_network as nn

# clf = fixclasses.FixClassifier()
clf = svm.SVC(probability=False, class_weight="balanced", C=1.29155, gamma='scale')
# clf = gp.GaussianProcess()
# clf = ensemble.RandomForestClassifier(n_estimators=50)
# clf = nn.MLPClassifier(solver='lbfgs', early_stopping=True)
# clf = ensemble.GradientBoostingClassifier()

clf = classify.train(training_data, loo=True)

TPR	TNR

	TPR	TNR	(3*TPR+TNR)/4
Mean	99.51	99.20	99.43
Median	100.00	99.50	99.80
Pooled	99.48	99.22	99.42

Pooled confusion matrix:
[[ 2314    12]
 [  161 20390]]

# Classify (single subject)

Apply a trained model to classify the independent components from a single subject.

In [146]:
from pyfix import classify
    
features0 = file_table.loc[0, 'features']
    
Y = classify.classify(features0, clf)
Y = np.where(Y==1)[0]+1

print(Y)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  23  24  25  27  28  29  31  33  35  36  37  38  39  40  42
  43  45  46  49  51  55  56  58  60  61  62  64  66  68  69  70  71  72
  73  74  76  77  78  79  80  81  82  83  84  85  86  87  92  93  94  95
  98 100 101 102 104 105 106 109 110 112 113 114 115 116 117 119 121 122
 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140
 141 142 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159
 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195
 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213
 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231
 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247]

# Apply (single subject)

Apply cleanup by regressing ICs labelled/classified as noise by FIX from the data.

In [116]:
with open('/Users/seanf/data/neofmri_2nd_release_rerun2/sub-CC00108XX09/ses-36800/fix/fix4melview_train35_thr10.txt', 'r') as f:
    ddremove = f.readlines()[-1]

ddremove = np.fromstring(ddremove.strip('[]\n'), dtype=int, sep=',')

print(ddremove)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  82  83  84  85  86  87  88  89  90  91  92
  93  94  95  96  97  98  99 100 101 102 103 104 106 107 108 109 110 111
 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129
 130 131 132 133 134 135 136 137 138 139 140 141 143 144 145 146 147 148
 149 151 152 153 154 155 156 157 158 159 160 161 162 163 165 166 167 168
 169 170 171 172 173 174 175 176 177 178 180 181 182 183 184 185 186 187
 188 190 191 192 193 194 195 196 198 199 200 201 202 203 204 205 206 207
 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225
 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243
 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261
 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279
 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297
 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315
 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333
 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351
 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368 369
 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386 387
 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403 404 405
 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 421 422 423
 424 425 426 427 428 429 430 431 432 433 434 435 436 437 438 439 440 441
 442 443 444 445 446 447 448 449 450 451 452 453 454 455 456 457 458 459
 460 461 462 463 464 465 466 467 468 469 470 471 472 473 474 475 476 477
 478 479 480 481 482 483 484 485 486 487 488 489 490 491 492 493 494 495
 496 497 498 499 500 501 502 503 504 505 506 507 508 509 510 511 512 513
 514 515 516 517 518 519 520 521 522 523 524 525 526 527 528 529 530 531
 532 533 534 535 536 537 538 539 540 541 542 543 544 545 546 547 548 549
 550 551 552 553 554 555 556 557 558 559 560 561 562 563 564 565 566 567
 568 569 570 571 572 573 574 575 576 577 578 579 580 581 582 583]

In [117]:
from pyfix import apply

apply.apply(
    funcname='/Users/seanf/data/neofmri_2nd_release_rerun2/sub-CC00108XX09/ses-36800/ica/func_filtered.nii.gz', 
    icamix='/Users/seanf/data/neofmri_2nd_release_rerun2/sub-CC00108XX09/ses-36800/ica/melodic_mix', 
    ddremove=np.array(ddremove), 
    temporal_fwhm=150, 
    motparams=None,
    filt_func=False, 
    filt_motparams=True, 
    func_tr=0.392, 
    outname='/Users/seanf/scratch/testing-pyfix/pyfix/func_clean.nii.gz',
)

In [118]:
! tree /Users/seanf/scratch/testing-pyfix/pyfix/

/Users/seanf/scratch/testing-pyfix/pyfix/
├── dummy2.nii.gz
├── dummyd.nii.gz
├── dummym.nii.gz
├── edge1.nii.gz
├── edge2.nii.gz
├── edge3.nii.gz
├── edge4.nii.gz
├── edge5.nii.gz
├── features.csv
├── func_clean.nii.gz
├── func_dseg.nii.gz
├── func_mean.nii.gz
├── func_std.nii.gz
├── func_tsnr.nii.gz
├── icmap0.nii.gz
├── icmap0_abs.nii.gz
├── maske1.nii.gz
├── maske2.nii.gz
├── maske3.nii.gz
├── maske4.nii.gz
├── maske5.nii.gz
├── std1mm2exfunc0.nii.gz
├── std1mm2exfunc0dil.nii.gz
├── std1mm2exfunc0dil2.nii.gz
├── std1mm2exfunc1.nii.gz
├── std1mm2exfunc1dil.nii.gz
├── std1mm2exfunc1dil2.nii.gz
├── std1mm2exfunc2.nii.gz
├── std1mm2exfunc2dil.nii.gz
├── std1mm2exfunc2dil2.nii.gz
├── std1mm2exfunc3.nii.gz
├── std1mm2exfunc3dil.nii.gz
├── std1mm2exfunc3dil2.nii.gz
├── std2func.mat
├── std2struct.mat
└── struct2std.mat

0 directories, 36 files